version: '1.0'
name: build
displayName: build
triggers:
  trigger: auto
  schedule:
    - cron: '* * 1 * * ? *'
stages:
  - name: build
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 24.13.0
        commands:
          - npm config set registry https://registry.npmmirror.com
          - npm install -g bun
          - bun run build
        caches: []
        notify: []
        strategy:
          retry: '0'
