name: Generate
on:
  schedule:
    - cron: '0 0 * * *'  # 每天的UTC时间0点触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: node --experimental-strip-types ./dnsResolve.ts
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add hosts.json hosts_deduped.json
          git commit -m 'Update hosts JSON'
          git push origin main
